name: test-vault-jwt
on:
  workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Vault using JWT
        run: |
          echo "Getting GitHub OIDC token..."

          TOKEN=$(curl -s \
            -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=vault" \
            | jq -r '.value')

          echo "Logging into Vault..."

          vault write auth/jwt/login \
            role=vault-jwt-access \
            jwt="$TOKEN"
